apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: example-app
metadata:
  annotations:
    description: deployment for Fuse AMQP client app
  name: example-app
objects:
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: example-app
      name: example-app
    spec:
      replicas: 1
      selector:
        app: example-app
      template:
        metadata:
          labels:
            app: example-app
        spec:
          containers:
            - name: example-app
              image: ' '
              ports:
                - containerPort: 8778
                  name: jolokia
              readinessProbe:
                httpGet:
                  path: actuator/health
                  port: 8081
                initialDelaySeconds: 10
              livenessProbe:
                httpGet:
                  path: actuator/health
                  port: 8081
                initialDelaySeconds: 180
              resources:
                limits:
                  cpu: "1.0"
                  memory: 256Mi
                requests:
                  cpu: "0.2"
                  memory: 256Mi
              volumeMounts:
                - name: application-config
                  mountPath: /deployments/config
          volumes:
            - name: application-config
              configMap:
                name: example-app
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: false
            containerNames:
              - example-app
            from:
              kind: ImageStreamTag
              name: example-app:${APPLICATION_IMAGE_TAG}
parameters:
  - name: APPLICATION_IMAGE_TAG
    value: latest
