apiVersion: v1
kind: List
items:
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: example-app-pipeline
    spec:
      source:
        git:
          uri: https://github.com/davgordo/example-app.git
          ref: per
      strategy:
        jenkinsPipelineStrategy:
          jenkinsfilePath: Jenkinsfile
      runPolicy: Parallel