apiVersion: v1
kind: List
items:
  - kind: RoleBinding
    apiVersion: v1
    metadata:
      name: jenkins-edit
      namespace: fuse-migration-dev
    roleRef:
      name: edit
    subjects:
      - kind: ServiceAccount
        name: jenkins
        namespace: fuse-migration-build
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: fuse-client-app-pipeline
    spec:
      source:
        git:
          uri: https://github.com/davgordo/fuse-client-app.git
          ref: arch
      strategy:
        jenkinsPipelineStrategy:
          jenkinsfilePath: Jenkinsfile
        runPolicy: Parallel