apiVersion: v1
kind: List
items:
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: fuse-client-app-pipeline
    spec:
      source:
        git:
          uri: https://github.com/davgordo/fuse-client-app.git
          ref: per
      strategy:
        jenkinsPipelineStrategy:
          jenkinsfilePath: Jenkinsfile
        runPolicy: Parallel